spring:
  application:
   name: activity-service
  data:
   mongodb:
     uri: mongodb://localhost:27017/activity-fitness
     database: ActivityType
  devtools:
    add-properties: true

server:
  port: 8008

logging:
  level:
    io.netty.resolver.dns: OFF


